Sex branch2
benoit-bremaud/HappiHub pull request #214
Opened 2024-07-22 14:39 UTC by viktor-argirov

2024-07-22 19:49 UTC, benoit-bremaud requested changes
Please take note of the comments and feedback provided during the code review. Your attention to these remarks is important to ensure the quality and consistency of the code before merging.

Thank you!

2024-07-22 19:51 UTC, benoit-bremaud commented
I would also like to get the opinions of @clement-machtelinckx  and @eva-razzini  on the comments I have made following the code review!

2024-07-23 15:28 UTC, clement-machtelinckx commented on client/src/components/Home/Home.jsx
> +        <button className="btn discover-btn" onClick={() => handleNavigate("/discover")}>Découvrir</button>
je ne suis pas sur de l'utilité de ces 3 bouton 

car en arrivant sur le home non connecter l'on a accès qu'aux pages connexion et inscription et ensuite après connexion les route accessible sont deja dans le header 

peut etre ajouter des card des evenement ou autre chose

2024-07-24 07:44 UTC, clement-machtelinckx commented on client/src/components/Event/event.css
> +  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
de plus la font ferrai plus de sens dans app.css pour avoir la font dans toute l'application au lieu de devoir remettre la fonte dans tout les composant

2024-07-24 11:14 UTC, benoit-bremaud approved these changes
good blowjob !!

2024-07-24 11:14 UTC, merged

2024-07-24 11:23 UTC, aicha-ouattara reviewed
ok